name: Deploy Backend to VPS (fixed)

on:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to Hostinger VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rsync and openssh-client
        run: sudo apt-get update -y && sudo apt-get install -y rsync openssh-client

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Rsync project to server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        run: |
          RSYNC_RSH="ssh -p ${SSH_PORT} -o IdentitiesOnly=yes -i ~/.ssh/id_rsa"
          rsync -az --exclude='.git' --exclude='node_modules' --exclude='.env' --exclude='.github' -e "$RSYNC_RSH" ./ ${SSH_USER}@${SSH_HOST}:${REMOTE_DIR}

      - name: Remote install & restart
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
          PM2_APP_NAME: ${{ secrets.PM2_APP_NAME }}
        run: |
          ssh -p ${SSH_PORT} -o IdentitiesOnly=yes -i ~/.ssh/id_rsa ${SSH_USER}@${SSH_HOST} "bash -lc 'cd \"${REMOTE_DIR}\" && if [ -f package-lock.json ]; then npm ci --omit=dev; else npm install --omit=dev; fi && if pm2 describe \"${PM2_APP_NAME}\" > /dev/null; then pm2 restart \"${PM2_APP_NAME}\" --update-env; else pm2 start index.js --name \"${PM2_APP_NAME}\" --update-env; fi && pm2 save && curl -fsS http://127.0.0.1:3001/ || exit 2'"
